name: Malachite Kernel Build

on:
  workflow_dispatch:
    inputs:
      with_kernelsu:
        description: 'Integrate KernelSU'
        required: true
        default: true
        type: boolean
      release:
        description: 'Create GitHub Release'
        required: true
        default: true
        type: boolean

jobs:
  build-kernel:
    name: Build Malachite Kernel
    runs-on: ubuntu-22.04
    timeout-minutes: 180

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/MiCode/Xiaomi_Kernel_OpenSource
          kernel-branch: malachite-u-oss
          config: gki_defconfig
          arch: arm64
          aosp-clang: true
          aosp-gcc: true
          android-version: 14
          aosp-clang-version: r487747c
          anykernel3: true
          release: ${{ inputs.release }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          extra-cmd: |
            export CONFIG_MTK_PLATFORM="mt6878"
            export CONFIG_ARCH_MEDIATEK=y
            export CONFIG_MTK_CPU_SUSPEND_EN=y
            export CONFIG_MTK_IRQ_NEW_DESIGN=y
            export CONFIG_MTK_PSCI=y
            export CONFIG_MTK_SCHED_RQ_AVG_KS=y
            export CONFIG_MTK_FREQ_HOPPING=y
            export CONFIG_MTK_GPU_SUPPORT=y
            export CONFIG_MALI_BIFROST=y
            export CONFIG_MALI_MIDGARD=y
            export CONFIG_MTK_CONN_LTE_IDC_SUPPORT=y
            export CONFIG_MTK_COMBO_CHIP_MT6631=y
            export CONFIG_LOCALVERSION="-Malachite-Custom"

